services:
  initializer:
    container_name: initializer
    stop_grace_period: 5m
    build:
      context: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      HOST: ${HOST}
      INTERNAL_PORT: ${INTERNAL_PORT}
      EXTERNAL_PORT: ${EXTERNAL_PORT}
      DIALECT: ${DIALECT}
      RESTORE_POINT_INTERVAL_MINUTES: ${RESTORE_POINT_INTERVAL_MINUTES}
      RESTORE_POINT_RETENTION: ${RESTORE_POINT_RETENTION}

    volumes:
      - restore:/app/restore
      - sql-scripts:/app/sql-scripts

volumes:
  restore:
    driver: local
    driver_opts:
      type: ${TYPE}
      device: "${RESTORE_POINT_DIRECTORY}"
      o: ${O}

  sql-scripts:
    driver: local
    driver_opts:
      type: ${TYPE}
      device: "${SQL_PROJECT_DIRECTORY}"
      o: ${O}