services:
  initializer:
    container_name: initializer # Name of the initializer container
    build:
      context: . 
    depends_on:
      db: # Database service must be healthy before starting the initializer
        condition: service_healthy
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      HOST: ${HOST}
      INTERNAL_PORT: ${INTERNAL_PORT}
      EXTERNAL_PORT: ${EXTERNAL_PORT}
      DIALECT: ${DIALECT}
      RESTORE_POINT_INTERVAL_MINUTES: ${RESTORE_POINT_INTERVAL_MINUTES}
      RESTORE_POINT_RETENTION: ${RESTORE_POINT_RETENTION}

    volumes:
      - restore:/app/restore
      - sql-scripts:/app/sql-scripts

volumes:
  restore:
  sql-scripts: